(u'Maj du', datetime.date(2017, 3, 16))
--------------------
Traceback (most recent call last):
  File "/home/ubuntu/Elections/metrics/scraping_networks_by_metric.py", line 193, in <module>
    save_metrics(get_metrics(), today)
  File "/home/ubuntu/Elections/metrics/scraping_networks_by_metric.py", line 94, in get_metrics
    print(candidate)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)
